services:
  - type: web
    name: procesador-planillas-excel
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    plan: free
    env: python
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /status
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1